/**
 * DigestCard Example
 * Demonstrates the DigestCard component with sample data
 */

import { DigestCard } from './DigestCard';
import type { FeedDigestMatch } from '@/types/feed';

// Sample digest match data
const sampleMatches: FeedDigestMatch[] = [
  {
    match: {
      id: 'match-1',
      sport: 'tennis',
      format: 'singles',
      score: { team1: 6, team2: 4 },
      winner_team: 1,
      score_status: 'confirmed',
      played_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      club_id: 'club-1',
      ladder_id: null,
      competition_id: null,
      competition_fixture_id: null,
      scheduled_at: null,
      score_submitted_by: 'user-1',
      score_confirmed_by: null,
      dispute_reason: null,
      notes: null,
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    opponent: {
      id: 'user-1',
      email: 'john.doe@example.com',
      full_name: 'John Doe',
      avatar_url: null,
      bio: 'Tennis player',
      phone: null,
      location_lat: 40.7128,
      location_lng: -74.006,
      location_city: 'New York',
      location_country: 'USA',
      home_club_id: 'club-1',
      onboarding_completed: true,
      dark_mode: false,
      push_notifications: true,
      email_notifications: true,
      last_seen: new Date().toISOString(),
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    club: {
      id: 'club-1',
      name: 'Central Park Tennis Club',
      description: 'Premier tennis club',
      address: '123 Park Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postal_code: '10001',
      location_lat: 40.7829,
      location_lng: -73.9654,
      phone: '555-0100',
      email: 'info@cptc.com',
      website: 'https://cptc.com',
      booking_url: null,
      logo_url: null,
      cover_image_url: null,
      is_claimed: false,
      claimed_by: null,
      sports: ['tennis'],
      amenities: ['Pro Shop', 'Locker Rooms'],
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    isWin: true,
  },
  {
    match: {
      id: 'match-2',
      sport: 'padel',
      format: 'doubles',
      score: { team1: 3, team2: 6 },
      winner_team: 2,
      score_status: 'confirmed',
      played_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      club_id: 'club-2',
      ladder_id: null,
      competition_id: null,
      competition_fixture_id: null,
      scheduled_at: null,
      score_submitted_by: 'user-2',
      score_confirmed_by: null,
      dispute_reason: null,
      notes: null,
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    opponent: {
      id: 'user-2',
      email: 'sarah.johnson@example.com',
      full_name: 'Sarah Johnson',
      avatar_url: null,
      bio: 'Padel enthusiast',
      phone: null,
      location_lat: 40.7589,
      location_lng: -73.9851,
      location_city: 'New York',
      location_country: 'USA',
      home_club_id: 'club-2',
      onboarding_completed: true,
      dark_mode: false,
      push_notifications: true,
      email_notifications: true,
      last_seen: new Date().toISOString(),
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    club: {
      id: 'club-2',
      name: 'Manhattan Padel Center',
      description: 'Modern padel facility',
      address: '456 Broadway',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postal_code: '10013',
      location_lat: 40.7589,
      location_lng: -73.9851,
      phone: '555-0200',
      email: 'info@mpc.com',
      website: 'https://mpc.com',
      booking_url: null,
      logo_url: null,
      cover_image_url: null,
      is_claimed: false,
      claimed_by: null,
      sports: ['padel'],
      amenities: ['Cafe', 'Parking'],
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    isWin: false,
  },
  {
    match: {
      id: 'match-3',
      sport: 'squash',
      format: 'singles',
      score: { team1: 11, team2: 8 },
      winner_team: 1,
      score_status: 'confirmed',
      played_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      club_id: 'club-3',
      ladder_id: null,
      competition_id: null,
      competition_fixture_id: null,
      scheduled_at: null,
      score_submitted_by: 'user-3',
      score_confirmed_by: null,
      dispute_reason: null,
      notes: null,
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    opponent: {
      id: 'user-3',
      email: 'mike.wilson@example.com',
      full_name: 'Mike Wilson',
      avatar_url: null,
      bio: 'Squash player',
      phone: null,
      location_lat: 40.7484,
      location_lng: -73.9857,
      location_city: 'New York',
      location_country: 'USA',
      home_club_id: 'club-3',
      onboarding_completed: true,
      dark_mode: false,
      push_notifications: true,
      email_notifications: true,
      last_seen: new Date().toISOString(),
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    club: {
      id: 'club-3',
      name: 'Empire Squash Club',
      description: 'Elite squash facility',
      address: '789 5th Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postal_code: '10022',
      location_lat: 40.7484,
      location_lng: -73.9857,
      phone: '555-0300',
      email: 'info@esc.com',
      website: 'https://esc.com',
      booking_url: null,
      logo_url: null,
      cover_image_url: null,
      is_claimed: false,
      claimed_by: null,
      sports: ['squash'],
      amenities: ['Lounge', 'Fitness Center'],
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    isWin: true,
  },
  {
    match: {
      id: 'match-4',
      sport: 'tennis',
      format: 'singles',
      score: { team1: 4, team2: 6 },
      winner_team: 2,
      score_status: 'confirmed',
      played_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      club_id: 'club-1',
      ladder_id: null,
      competition_id: null,
      competition_fixture_id: null,
      scheduled_at: null,
      score_submitted_by: 'user-4',
      score_confirmed_by: null,
      dispute_reason: null,
      notes: null,
      created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    opponent: {
      id: 'user-4',
      email: 'emma.davis@example.com',
      full_name: 'Emma Davis',
      avatar_url: null,
      bio: 'Tennis coach',
      phone: null,
      location_lat: 40.7128,
      location_lng: -74.006,
      location_city: 'New York',
      location_country: 'USA',
      home_club_id: 'club-1',
      onboarding_completed: true,
      dark_mode: false,
      push_notifications: true,
      email_notifications: true,
      last_seen: new Date().toISOString(),
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    club: {
      id: 'club-1',
      name: 'Central Park Tennis Club',
      description: 'Premier tennis club',
      address: '123 Park Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postal_code: '10001',
      location_lat: 40.7829,
      location_lng: -73.9654,
      phone: '555-0100',
      email: 'info@cptc.com',
      website: 'https://cptc.com',
      booking_url: null,
      logo_url: null,
      cover_image_url: null,
      is_claimed: false,
      claimed_by: null,
      sports: ['tennis'],
      amenities: ['Pro Shop', 'Locker Rooms'],
      created_at: '2023-01-01T00:00:00Z',
      updated_at: new Date().toISOString(),
    },
    isWin: false,
  },
];

export function DigestCardExample() {
  return (
    <div style={{ padding: 20, background: 'var(--color-bg)', minHeight: '100vh' }}>
      <h1 style={{ marginBottom: 20 }}>DigestCard Examples</h1>

      <h2 style={{ marginTop: 30, marginBottom: 10 }}>Weekly Match Digest (4 matches)</h2>
      <DigestCard matches={sampleMatches} />

      <h2 style={{ marginTop: 30, marginBottom: 10 }}>Single Match</h2>
      <DigestCard matches={[sampleMatches[0]]} />

      <h2 style={{ marginTop: 30, marginBottom: 10 }}>Two Matches (Win and Loss)</h2>
      <DigestCard matches={[sampleMatches[0], sampleMatches[1]]} />

      <h2 style={{ marginTop: 30, marginBottom: 10 }}>Empty State (No Matches)</h2>
      <DigestCard matches={[]} />
      <p style={{ color: 'var(--color-t2)', fontSize: 14, marginTop: 10 }}>
        Note: Empty digest cards return null and don't render anything
      </p>
    </div>
  );
}
